[package]
name = "downsample-server"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
arrow = "55.2.0"
log = "0.4.27"
pretty_env_logger = "0.5.0"
serde = "1.0.219"
thiserror = "2.0.12"
tokio = "1.46.0"
